"use strict";
var ptg = ThisCouldBeBetter.PlanetTopographyGenerator;
var PlanetTopographyGenerator = ptg.PlanetTopographyGenerator;
var Camera = ptg.Camera;
var Constraint_LookAtBody = ptg.Constraint_LookAtBody;
var Constraint_MaintainDistance = ptg.Constraint_MaintainDistance;
var Coords = ptg.Coords;
var Display = ptg.Display;
var Disposition = ptg.Disposition;
var Empty = ptg.Empty;
var Globals = ptg.Globals;
var InputHelper = ptg.InputHelper;
var Mesh = ptg.Mesh;
var MeshHelper = ptg.MeshHelper;
var Orientation = ptg.Orientation;
var Plane = ptg.Plane;
var Scene = ptg.Scene;
var Vertex = ptg.Vertex;
